#pragma once
// GENERATED by tools/gen_codec.py — do not hand-edit.
// Real registry/codec NBT from minecraft-data loginPacket.json
// (filtered: overworld + plains + chat + damage; vanilla IDs kept).
#include <cstddef>
#include <cstdint>

namespace limbo::codec {

struct Blob { const uint8_t* data; size_t size; };
Blob j116();
Blob j1162();
Blob dim_1162();
Blob j117();
Blob dim_117();
Blob j118();
Blob dim_118();
Blob j119_759();
Blob dim_119_759();
Blob j119_760();
Blob dim_119_760();
Blob j119_7612();
Blob dim_119_7612();
Blob j120_763();
Blob dim_120_763();
Blob c764();
Blob c765();
Blob e766_dimension_type();
Blob e766_biome();
Blob e766_chat_type();
Blob e766_damage_type();
Blob e767_dimension_type();
Blob e767_biome();
Blob e767_chat_type();
Blob e767_damage_type();
Blob e769_dimension_type();
Blob e769_biome();
Blob e769_chat_type();
Blob e769_damage_type();
Blob e770_dimension_type();
Blob e770_biome();
Blob e770_chat_type();
Blob e770_damage_type();
Blob e773_dimension_type();
Blob e773_biome();
Blob e773_chat_type();
Blob e773_damage_type();
Blob e774_dimension_type();
Blob e774_biome();
Blob e774_chat_type();
Blob e774_damage_type();
Blob e775_dimension_type();
Blob e775_biome();
Blob e775_chat_type();
Blob e775_damage_type();
int plainsId(const char* target);
int overworldId(const char* target);
}  // namespace limbo::codec
