# limbo-c++ — proprietary software, all rights reserved.
# Copyright (c) 2026 Paranthaman
# See LICENSE. No permission is granted to copy, modify, or redistribute
# this file. Contact Paranthaman-K6@users.noreply.github.com for permission.

#!/usr/bin/env python3
"""Prepend the limbo-c++ proprietary copyright header to first-party sources.

A copied file should carry the notice with it -- that is what makes the
reservation travel when someone pastes a single .cpp somewhere.

Deliberately skipped:
  third_party/**  public domain (CC0); a proprietary header would contradict
                  its own terms.
  **/codec_data.* generated by tools/gen_codec.py; the generator emits the
                  header itself so regeneration does not drop it.

Idempotent: a file that already contains the marker is left untouched.

Usage: python3 tools/add_copyright_header.py [--check] [repo_root]
  --check  exit 1 if any first-party file is missing the header
"""
from __future__ import annotations

import pathlib
import sys

MARKER = "Copyright (c) 2026 Paranthaman"

HEADER_TEXT = (
    "limbo-c++ — proprietary software, all rights reserved.\n"
    f"{MARKER}\n"
    "See LICENSE. No permission is granted to copy, modify, or redistribute\n"
    "this file. Contact Paranthaman-K6@users.noreply.github.com for permission.\n"
)

# (glob, comment prefix)
TARGETS = [
    ("src/**/*.cpp", "//"),
    ("src/**/*.h", "//"),
    ("tests/**/*.cpp", "//"),
    ("tests/**/*.h", "//"),
    ("tests/**/*.py", "#"),
    ("tools/**/*.py", "#"),
    ("Makefile", "#"),
]

# paths (relative, POSIX) that must never get the header
SKIP_SUBSTRINGS = ("third_party/", "codec_data.")


def header_for(prefix: str) -> str:
    lines = HEADER_TEXT.rstrip("\n").split("\n")
    return "\n".join(f"{prefix} {ln}" if ln else f"{prefix}" for ln in lines) + "\n\n"


def iter_targets(root: pathlib.Path):
    for pattern, prefix in TARGETS:
        for path in sorted(root.glob(pattern)):
            rel = path.relative_to(root).as_posix()
            if any(s in rel for s in SKIP_SUBSTRINGS):
                continue
            yield path, prefix


def main() -> int:
    check_only = "--check" in sys.argv
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    root = pathlib.Path(args[0]).resolve() if args else pathlib.Path(__file__).resolve().parent.parent

    changed, already, missing = [], [], []
    for path, prefix in iter_targets(root):
        text = path.read_text(encoding="utf-8")
        rel = path.relative_to(root)
        if MARKER in text.split("\n\n")[0] or text.startswith(f"{prefix} limbo-c++"):
            already.append(rel)
            continue
        missing.append(rel)
        if not check_only:
            path.write_text(header_for(prefix) + text, encoding="utf-8")
            changed.append(rel)

    if check_only:
        if missing:
            print("missing copyright header:", file=sys.stderr)
            for m in missing:
                print(f"  {m}", file=sys.stderr)
            return 1
        print(f"all {len(already)} first-party files carry the notice")
        return 0

    print(f"added header to {len(changed)} file(s)")
    for c in changed:
        print(f"  + {c}")
    print(f"already had it: {len(already)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
